### Health
GET http://localhost:8000/health

### Analyze
POST http://localhost:8000/api/v1/regex/analyze
Content-Type: application/json

{
  "regex": "(a|b)*abb",
  "active_page": 0
}

### Figure (page 3)
POST http://localhost:8000/api/v1/regex/figure
Content-Type: application/json

{
  "regex": "(a|b)*abb",
  "active_page": 3
}
